# configure task definition readers
readerConfig:
  # name of the reader
  filereader:
    # reader implementation class name to load tasks
    readerClass: com.cognitree.kronos.scheduler.readers.FileTaskDefinitionReader
    config:
      # file to look in classpath to load task definitions
      source: task-definitions.yaml
    # interval in cron to look for changes in the task definition file
    schedule: 0 0/1 * 1/1 * ? *

# configure task handlers
handlerConfig:
  # type of task to be handled by handler
  shellCommand:
    # handler implementation used to handle task of type shellCommand
    handlerClass: com.cognitree.kronos.executor.handlers.ShellCommandHandler
    # max execution time per task
    maxExecutionTime: 10m
    # max parallel tasks handler is allowed to execute at any point of time
    maxParallelTasks: 4

# configure message bus
taskProducerConfig:
  producerClass: com.cognitree.kronos.queue.producer.InMemoryTaskProducer
taskConsumerConfig:
  consumerClass: com.cognitree.kronos.queue.consumer.InMemoryTaskConsumer
  config:
    pollInterval: 10s # time interval to poll tasks from task queue for execution
taskStatusProducerConfig:
  producerClass: com.cognitree.kronos.queue.producer.InMemoryStatusProducer
taskStatusConsumerConfig:
  consumerClass: com.cognitree.kronos.queue.consumer.InMemoryStatusConsumer
  config:
    pollInterval: 10s # time interval to poll tasks status from status queue

# configure task store
taskStoreConfig:
  taskStoreClass: com.cognitree.kronos.store.SQLiteTaskStore
  config:
    connectionURL: jdbc:sqlite:/Users/ankitnanglia/sample.db
    username:
    password:

# time to wait before removing executed tasks from memory
taskPurgeInterval: 1d